/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as YtOrderTimingImport } from './routes/yt-order-timing'
import { Route as OrderPredictionImport } from './routes/order-prediction'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const YtOrderTimingRoute = YtOrderTimingImport.update({
  path: '/yt-order-timing',
  getParentRoute: () => rootRoute,
} as any)

const OrderPredictionRoute = OrderPredictionImport.update({
  path: '/order-prediction',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/order-prediction': {
      id: '/order-prediction'
      path: '/order-prediction'
      fullPath: '/order-prediction'
      preLoaderRoute: typeof OrderPredictionImport
      parentRoute: typeof rootRoute
    }
    '/yt-order-timing': {
      id: '/yt-order-timing'
      path: '/yt-order-timing'
      fullPath: '/yt-order-timing'
      preLoaderRoute: typeof YtOrderTimingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/order-prediction': typeof OrderPredictionRoute
  '/yt-order-timing': typeof YtOrderTimingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/order-prediction': typeof OrderPredictionRoute
  '/yt-order-timing': typeof YtOrderTimingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/order-prediction': typeof OrderPredictionRoute
  '/yt-order-timing': typeof YtOrderTimingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/order-prediction' | '/yt-order-timing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/order-prediction' | '/yt-order-timing'
  id: '__root__' | '/' | '/about' | '/order-prediction' | '/yt-order-timing'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OrderPredictionRoute: typeof OrderPredictionRoute
  YtOrderTimingRoute: typeof YtOrderTimingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OrderPredictionRoute: OrderPredictionRoute,
  YtOrderTimingRoute: YtOrderTimingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/order-prediction",
        "/yt-order-timing"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/order-prediction": {
      "filePath": "order-prediction.tsx"
    },
    "/yt-order-timing": {
      "filePath": "yt-order-timing.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
